### ISSUE TITLE
Logging of ReflectionTypeLoadExceptions

### ISSUE THREAD

**Issue by neochrome** [drunkcod/Cone#20]
It would be very convenient if cone could trap and log ReflectionTypeLoadException so that one don't have to put the Verify's in a try-catch if that problem occurs. Example logging:

```
catch (ReflectionTypeLoadException ex)
{
  Console.Error.WriteLine(ex.Message);
  foreach (var loaderException in ex.LoaderExceptions)
  {
    Console.Error.WriteLine(loaderException.Message);
  }
}
```

**Comment by drunkcod** [comment]
This should have been closed years ago.
