### ISSUE TITLE
TestAdapter as nuget package

### ISSUE THREAD

**Issue by mattyas** [drunkcod/Cone#33]
Since your TestAdapter uses .dll files and not a custom test container discoverer you should be able to distribute it as a nuget package, removing the need to install a vsix on the computer.

Old way is just to put the Cone.TestAdapter.dll in the tools folder of the package,
new one is to put the Cone.TestAdapter.dll in build\net35, build\netcoreapp1.0 etc.

**Comment by drunkcod** [comment]
Excellent suggestion. I'll wrap this up and hopefully publish it during the week.
